In [1]:
import pandas as pd
import numpy as np

from pathlib import Path

In [2]:
input_file = Path("clinical_feature_engineered_data.xlsx")
output_file = Path("patient_disease_medicine_data.xlsx")

print("Input file:", input_file)
print("Output file:", output_file)

Input file: clinical_feature_engineered_data.xlsx
Output file: patient_disease_medicine_data.xlsx

In [3]:
if not input_file.exists():
    raise FileNotFoundError(
        f"Day 6 output file was not found: {input_file}"
    )

print("Day 6 file found successfully.")

Day 6 file found successfully.

In [4]:
excel_file = pd.ExcelFile(input_file)

print("Available sheets:")
print(excel_file.sheet_names)

Available sheets:
['Feature_Engineered_Data', 'Model_Features', 'Target']

In [5]:
df = pd.read_excel(
    input_file,
    sheet_name="Feature_Engineered_Data"
)

print("Dataset shape:", df.shape)
print("\nColumns:")
print(df.columns.tolist())

Dataset shape: (500, 31)

Columns:
['patient_id', 'age_years', 'sex', 'condition', 'glucose_mg_dl', 'systolic_bp_mmhg', 'diastolic_bp_mmhg', 'cholesterol_mg_dl', 'heart_rate_bpm', 'recorded_allergy', 'family_history', 'adherence_level', 'historical_medication_class', 'recorded_outcome', 'data_quality_status', 'age_group', 'pulse_pressure_mmhg', 'systolic_diastolic_ratio', 'glucose_cholesterol_interaction', 'glucose_age_interaction', 'cholesterol_age_interaction', 'bp_age_interaction', 'allergy_recorded_flag', 'family_history_flag', 'adherence_score', 'glucose_mg_dl_dataset_zscore', 'systolic_bp_mmhg_dataset_zscore', 'diastolic_bp_mmhg_dataset_zscore', 'cholesterol_mg_dl_dataset_zscore', 'heart_rate_bpm_dataset_zscore', 'measurement_deviation_score']

In [6]:
df.head()

,patient_id,age_years,sex,condition,glucose_mg_dl,systolic_bp_mmhg,diastolic_bp_mmhg,cholesterol_mg_dl,heart_rate_bpm,recorded_allergy,...,bp_age_interaction,allergy_recorded_flag,family_history_flag,adherence_score,glucose_mg_dl_dataset_zscore,systolic_bp_mmhg_dataset_zscore,diastolic_bp_mmhg_dataset_zscore,cholesterol_mg_dl_dataset_zscore,heart_rate_bpm_dataset_zscore,measurement_deviation_score
0,SYN-0001,28,Female,Seasonal Allergy,97,132,85,214,73,None recorded,...,3696,0,0,2,-0.324226,0.254356,0.339338,0.424061,-0.315852,0.331566
1,SYN-0002,80,Female,Acid Reflux,80,123,79,189,59,None recorded,...,9840,0,1,1,-0.809337,-0.237734,-0.210049,-0.216205,-1.546215,0.603908
2,SYN-0003,36,Female,Asthma,86,121,66,192,82,None recorded,...,4356,0,0,1,-0.638121,-0.347087,-1.400387,-0.139373,0.475096,0.600013
3,SYN-0004,21,Male,High Cholesterol,103,120,69,278,85,None recorded,...,2520,0,1,2,-0.153010,-0.401764,-1.125693,2.063142,0.738745,0.896471
4,SYN-0005,58,Male,High Cholesterol,79,111,76,244,64,None recorded,...,6438,0,1,2,-0.837873,-0.893854,-0.484742,1.192380,-1.106799,0.903130

In [7]:
print("Dataset Information")
print("=" * 50)

print("Rows:", df.shape[0])
print("Columns:", df.shape[1])

print("\nData Types:")
print(df.dtypes)

Dataset Information
==================================================
Rows: 500
Columns: 31

Data Types:
patient_id                           object
age_years                             int64
sex                                  object
condition                            object
glucose_mg_dl                         int64
systolic_bp_mmhg                      int64
diastolic_bp_mmhg                     int64
cholesterol_mg_dl                     int64
heart_rate_bpm                        int64
recorded_allergy                     object
family_history                       object
adherence_level                      object
historical_medication_class          object
recorded_outcome                     object
data_quality_status                  object
age_group                            object
pulse_pressure_mmhg                   int64
systolic_diastolic_ratio            float64
glucose_cholesterol_interaction       int64
glucose_age_interaction               int64
cholesterol_age_interaction           int64
bp_age_interaction                    int64
allergy_recorded_flag                 int64
family_history_flag                   int64
adherence_score                       int64
glucose_mg_dl_dataset_zscore        float64
systolic_bp_mmhg_dataset_zscore     float64
diastolic_bp_mmhg_dataset_zscore    float64
cholesterol_mg_dl_dataset_zscore    float64
heart_rate_bpm_dataset_zscore       float64
measurement_deviation_score         float64
dtype: object

In [8]:
patient_column = "patient_id"
disease_column = "condition"
medicine_column = "historical_medication_class"

required_columns = [
    patient_column,
    disease_column,
    medicine_column
]

missing_columns = [
    column for column in required_columns
    if column not in df.columns
]

if missing_columns:
    raise ValueError(
        f"Required columns are missing: {missing_columns}"
    )

print("Required columns verified successfully.")
print(required_columns)

Required columns verified successfully.
['patient_id', 'condition', 'historical_medication_class']

In [9]:
patient_disease_medicine = df[
    [
        patient_column,
        disease_column,
        medicine_column
    ]
].copy()

patient_disease_medicine.columns = [
    "patient_id",
    "disease",
    "medicine_class"
]

print("Patient–Disease–Medicine dataset shape:")
print(patient_disease_medicine.shape)

Patient–Disease–Medicine dataset shape:
(500, 3)

In [10]:
patient_disease_medicine.head(10)

  patient_id           disease            medicine_class
0   SYN-0001  Seasonal Allergy     Antihistamine class A
1   SYN-0002       Acid Reflux  Acid-suppression class A
2   SYN-0003            Asthma  Controller inhaler class
3   SYN-0004  High Cholesterol    Lipid-lowering class B
4   SYN-0005  High Cholesterol    Lipid-lowering class B
5   SYN-0006      Hypertension  Antihypertensive class B
6   SYN-0007   Type 2 Diabetes      Antidiabetic class B
7   SYN-0008            Asthma      Bronchodilator class
8   SYN-0009  Seasonal Allergy     Antihistamine class A
9   SYN-0010       Acid Reflux  Acid-suppression class A

In [11]:
missing_relationship_values = (
    patient_disease_medicine.isnull().sum()
)

print("Missing values:")
print(missing_relationship_values)

Missing values:
patient_id        0
disease           0
medicine_class    0
dtype: int64

In [12]:
blank_value_counts = (
    patient_disease_medicine
    .astype(str)
    .apply(lambda column: column.str.strip().eq("").sum())
)

print("Blank values:")
print(blank_value_counts)

Blank values:
patient_id        0
disease           0
medicine_class    0
dtype: int64

In [13]:
unique_patients = (
    patient_disease_medicine["patient_id"]
    .nunique()
)

print("Total records:", len(patient_disease_medicine))
print("Unique patients:", unique_patients)

Total records: 500
Unique patients: 500

In [14]:
duplicate_relationships = (
    patient_disease_medicine
    .duplicated()
    .sum()
)

print("Duplicate Patient–Disease–Medicine relationships:")
print(duplicate_relationships)

Duplicate Patient–Disease–Medicine relationships:
0

In [15]:
duplicate_rows = (
    patient_disease_medicine[
        patient_disease_medicine.duplicated(keep=False)
    ]
    .sort_values(
        ["patient_id", "disease", "medicine_class"]
    )
)

duplicate_rows.head(20)

Empty DataFrame
Columns: [patient_id, disease, medicine_class]
Index: []

In [16]:
patient_disease_medicine_unique = (
    patient_disease_medicine
    .drop_duplicates()
    .reset_index(drop=True)
)

print(
    "Unique Patient–Disease–Medicine records:",
    len(patient_disease_medicine_unique)
)

Unique Patient–Disease–Medicine records: 500

In [17]:
disease_medicine_map = (
    patient_disease_medicine_unique[
        ["disease", "medicine_class"]
    ]
    .drop_duplicates()
    .sort_values(
        ["disease", "medicine_class"]
    )
    .reset_index(drop=True)
)

print("Disease–Medicine mapping:")
print(disease_medicine_map)

Disease–Medicine mapping:
             disease            medicine_class
0        Acid Reflux  Acid-suppression class A
1        Acid Reflux  Acid-suppression class B
2             Asthma      Bronchodilator class
3             Asthma  Controller inhaler class
4   High Cholesterol    Lipid-lowering class A
5   High Cholesterol    Lipid-lowering class B
6       Hypertension  Antihypertensive class A
7       Hypertension  Antihypertensive class B
8   Seasonal Allergy     Antihistamine class A
9   Seasonal Allergy     Antihistamine class B
10   Type 2 Diabetes      Antidiabetic class A
11   Type 2 Diabetes      Antidiabetic class B

In [18]:
disease_medicine_counts = (
    patient_disease_medicine_unique
    .groupby(
        ["disease", "medicine_class"],
        as_index=False
    )
    .agg(
        patient_count=("patient_id", "nunique")
    )
    .sort_values(
        "patient_count",
        ascending=False
    )
    .reset_index(drop=True)
)

disease_medicine_counts.head(20)

             disease            medicine_class  patient_count
0   Seasonal Allergy     Antihistamine class A             52
1             Asthma  Controller inhaler class             47
2    Type 2 Diabetes      Antidiabetic class A             45
3       Hypertension  Antihypertensive class A             43
4        Acid Reflux  Acid-suppression class A             42
5   High Cholesterol    Lipid-lowering class A             42
6       Hypertension  Antihypertensive class B             42
7    Type 2 Diabetes      Antidiabetic class B             42
8   Seasonal Allergy     Antihistamine class B             40
9             Asthma      Bronchodilator class             36
10       Acid Reflux  Acid-suppression class B             35
11  High Cholesterol    Lipid-lowering class B             34

In [19]:
number_of_diseases = (
    patient_disease_medicine_unique["disease"]
    .nunique()
)

print("Number of unique diseases/conditions:")
print(number_of_diseases)

Number of unique diseases/conditions:
6

In [20]:
number_of_medicine_classes = (
    patient_disease_medicine_unique["medicine_class"]
    .nunique()
)

print("Number of unique medication classes:")
print(number_of_medicine_classes)

Number of unique medication classes:
12

In [21]:
patient_disease = (
    patient_disease_medicine_unique[
        ["patient_id", "disease"]
    ]
    .drop_duplicates()
    .sort_values(
        ["patient_id", "disease"]
    )
    .reset_index(drop=True)
)

print("Patient–Disease table shape:")
print(patient_disease.shape)

Patient–Disease table shape:
(500, 2)

In [22]:
patient_count_by_disease = (
    patient_disease
    .groupby("disease", as_index=False)
    .agg(
        patient_count=("patient_id", "nunique")
    )
    .sort_values(
        "patient_count",
        ascending=False
    )
    .reset_index(drop=True)
)

patient_count_by_disease

            disease  patient_count
0  Seasonal Allergy             92
1   Type 2 Diabetes             87
2      Hypertension             85
3            Asthma             83
4       Acid Reflux             77
5  High Cholesterol             76

In [23]:
total_unique_patients = (
    patient_disease["patient_id"]
    .nunique()
)

patient_count_by_disease["patient_percentage"] = (
    patient_count_by_disease["patient_count"]
    / total_unique_patients
    * 100
)

patient_count_by_disease[
    "patient_percentage"
] = patient_count_by_disease[
    "patient_percentage"
].round(2)

patient_count_by_disease

            disease  patient_count  patient_percentage
0  Seasonal Allergy             92                18.4
1   Type 2 Diabetes             87                17.4
2      Hypertension             85                17.0
3            Asthma             83                16.6
4       Acid Reflux             77                15.4
5  High Cholesterol             76                15.2

In [24]:
disease_summary = (
    patient_disease_medicine_unique
    .groupby("disease")
    .agg(
        patient_count=("patient_id", "nunique"),
        medicine_class_count=("medicine_class", "nunique")
    )
    .reset_index()
    .sort_values(
        "patient_count",
        ascending=False
    )
    .reset_index(drop=True)
)

disease_summary

            disease  patient_count  medicine_class_count
0  Seasonal Allergy             92                     2
1   Type 2 Diabetes             87                     2
2      Hypertension             85                     2
3            Asthma             83                     2
4       Acid Reflux             77                     2
5  High Cholesterol             76                     2

In [25]:
medicine_class_summary = (
    patient_disease_medicine_unique
    .groupby("medicine_class")
    .agg(
        patient_count=("patient_id", "nunique"),
        disease_count=("disease", "nunique")
    )
    .reset_index()
    .sort_values(
        "patient_count",
        ascending=False
    )
    .reset_index(drop=True)
)

medicine_class_summary

              medicine_class  patient_count  disease_count
0      Antihistamine class A             52              1
1   Controller inhaler class             47              1
2       Antidiabetic class A             45              1
3   Antihypertensive class A             43              1
4   Acid-suppression class A             42              1
5       Antidiabetic class B             42              1
6   Antihypertensive class B             42              1
7     Lipid-lowering class A             42              1
8      Antihistamine class B             40              1
9       Bronchodilator class             36              1
10  Acid-suppression class B             35              1
11    Lipid-lowering class B             34              1

In [26]:
medicine_distribution = (
    patient_disease_medicine_unique[
        "medicine_class"
    ]
    .value_counts()
    .rename_axis("medicine_class")
    .reset_index(name="patient_count")
)

medicine_distribution

              medicine_class  patient_count
0      Antihistamine class A             52
1   Controller inhaler class             47
2       Antidiabetic class A             45
3   Antihypertensive class A             43
4   Acid-suppression class A             42
5   Antihypertensive class B             42
6       Antidiabetic class B             42
7     Lipid-lowering class A             42
8      Antihistamine class B             40
9       Bronchodilator class             36
10  Acid-suppression class B             35
11    Lipid-lowering class B             34

In [27]:
medicine_distribution["percentage"] = (
    medicine_distribution["patient_count"]
    / medicine_distribution["patient_count"].sum()
    * 100
)

medicine_distribution["percentage"] = (
    medicine_distribution["percentage"]
    .round(2)
)

medicine_distribution

              medicine_class  patient_count  percentage
0      Antihistamine class A             52        10.4
1   Controller inhaler class             47         9.4
2       Antidiabetic class A             45         9.0
3   Antihypertensive class A             43         8.6
4   Acid-suppression class A             42         8.4
5   Antihypertensive class B             42         8.4
6       Antidiabetic class B             42         8.4
7     Lipid-lowering class A             42         8.4
8      Antihistamine class B             40         8.0
9       Bronchodilator class             36         7.2
10  Acid-suppression class B             35         7.0
11    Lipid-lowering class B             34         6.8

In [28]:
disease_medicine_relationship_count = (
    disease_medicine_map
    .groupby("disease")
    .agg(
        medicine_class_count=("medicine_class", "nunique")
    )
    .reset_index()
    .sort_values(
        "medicine_class_count",
        ascending=False
    )
)

disease_medicine_relationship_count

            disease  medicine_class_count
0       Acid Reflux                     2
1            Asthma                     2
2  High Cholesterol                     2
3      Hypertension                     2
4  Seasonal Allergy                     2
5   Type 2 Diabetes                     2

In [29]:
for disease, group in disease_medicine_map.groupby("disease"):
    
    medicines = group["medicine_class"].tolist()
    
    print(f"\nDisease: {disease}")
    
    for medicine in medicines:
        print(f"  → {medicine}")

Disease: Acid Reflux
  → Acid-suppression class A
  → Acid-suppression class B

Disease: Asthma
  → Bronchodilator class
  → Controller inhaler class

Disease: High Cholesterol
  → Lipid-lowering class A
  → Lipid-lowering class B

Disease: Hypertension
  → Antihypertensive class A
  → Antihypertensive class B

Disease: Seasonal Allergy
  → Antihistamine class A
  → Antihistamine class B

Disease: Type 2 Diabetes
  → Antidiabetic class A
  → Antidiabetic class B

In [30]:
patient_validation = (
    patient_disease_medicine_unique
    .groupby("patient_id")
    .agg(
        disease_count=("disease", "nunique"),
        medicine_class_count=("medicine_class", "nunique")
    )
    .reset_index()
)

patient_validation.head()

  patient_id  disease_count  medicine_class_count
0   SYN-0001              1                     1
1   SYN-0002              1                     1
2   SYN-0003              1                     1
3   SYN-0004              1                     1
4   SYN-0005              1                     1

In [31]:
patients_without_disease = (
    patient_disease_medicine_unique[
        patient_disease_medicine_unique["disease"].isna()
    ]
)

print(
    "Patients without disease information:",
    len(patients_without_disease)
)

Patients without disease information: 0

In [32]:
patients_without_medicine = (
    patient_disease_medicine_unique[
        patient_disease_medicine_unique["medicine_class"].isna()
    ]
)

print(
    "Patients without medication-class information:",
    len(patients_without_medicine)
)

Patients without medication-class information: 0

In [33]:
validation_report = pd.DataFrame({
    "metric": [
        "Original Day 7 records",
        "Unique patients",
        "Unique diseases/conditions",
        "Unique medication classes",
        "Unique Patient-Disease relationships",
        "Unique Patient-Disease-Medicine relationships",
        "Duplicate Patient-Disease-Medicine rows",
        "Missing patient IDs",
        "Missing diseases",
        "Missing medication classes"
    ],
    "value": [
        len(patient_disease_medicine),
        patient_disease_medicine_unique["patient_id"].nunique(),
        patient_disease_medicine_unique["disease"].nunique(),
        patient_disease_medicine_unique["medicine_class"].nunique(),
        len(patient_disease),
        len(patient_disease_medicine_unique),
        duplicate_relationships,
        patient_disease_medicine_unique["patient_id"].isna().sum(),
        patient_disease_medicine_unique["disease"].isna().sum(),
        patient_disease_medicine_unique["medicine_class"].isna().sum()
    ]
})

validation_report

                                          metric  value
0                         Original Day 7 records    500
1                                Unique patients    500
2                     Unique diseases/conditions      6
3                      Unique medication classes     12
4           Unique Patient-Disease relationships    500
5  Unique Patient-Disease-Medicine relationships    500
6        Duplicate Patient-Disease-Medicine rows      0
7                            Missing patient IDs      0
8                               Missing diseases      0
9                     Missing medication classes      0

In [34]:
assert (
    patient_disease_medicine_unique["patient_id"]
    .notna()
    .all()
)

assert (
    patient_disease_medicine_unique["disease"]
    .notna()
    .all()
)

assert (
    patient_disease_medicine_unique["medicine_class"]
    .notna()
    .all()
)

assert (
    patient_disease_medicine_unique
    .duplicated()
    .sum()
    == 0
)

print("All Patient–Disease–Medicine validation checks passed successfully.")

All Patient–Disease–Medicine validation checks passed successfully.

In [35]:
patient_disease_medicine_unique.head(10)

  patient_id           disease            medicine_class
0   SYN-0001  Seasonal Allergy     Antihistamine class A
1   SYN-0002       Acid Reflux  Acid-suppression class A
2   SYN-0003            Asthma  Controller inhaler class
3   SYN-0004  High Cholesterol    Lipid-lowering class B
4   SYN-0005  High Cholesterol    Lipid-lowering class B
5   SYN-0006      Hypertension  Antihypertensive class B
6   SYN-0007   Type 2 Diabetes      Antidiabetic class B
7   SYN-0008            Asthma      Bronchodilator class
8   SYN-0009  Seasonal Allergy     Antihistamine class A
9   SYN-0010       Acid Reflux  Acid-suppression class A

In [36]:
print("Final Patient–Disease–Medicine Dataset")
print("=" * 60)

print("Rows:", patient_disease_medicine_unique.shape[0])
print("Columns:", patient_disease_medicine_unique.shape[1])

print("\nColumns:")
print(patient_disease_medicine_unique.columns.tolist())

print("\nData types:")
print(patient_disease_medicine_unique.dtypes)

Final Patient–Disease–Medicine Dataset
============================================================
Rows: 500
Columns: 3

Columns:
['patient_id', 'disease', 'medicine_class']

Data types:
patient_id        object
disease           object
medicine_class    object
dtype: object

In [37]:
with pd.ExcelWriter(
    output_file,
    engine="openpyxl"
) as writer:

    patient_disease_medicine_unique.to_excel(
        writer,
        sheet_name="Patient_Disease_Medicine",
        index=False
    )

    disease_medicine_map.to_excel(
        writer,
        sheet_name="Disease_Medicine_Map",
        index=False
    )

    patient_disease.to_excel(
        writer,
        sheet_name="Patient_Disease",
        index=False
    )

    patient_count_by_disease.to_excel(
        writer,
        sheet_name="Disease_Patient_Summary",
        index=False
    )

    disease_summary.to_excel(
        writer,
        sheet_name="Disease_Summary",
        index=False
    )

    medicine_class_summary.to_excel(
        writer,
        sheet_name="Medicine_Summary",
        index=False
    )

    medicine_distribution.to_excel(
        writer,
        sheet_name="Medicine_Distribution",
        index=False
    )

    disease_medicine_counts.to_excel(
        writer,
        sheet_name="Disease_Medicine_Counts",
        index=False
    )

    validation_report.to_excel(
        writer,
        sheet_name="Validation_Report",
        index=False
    )

print("Day 7 workbook saved successfully:")
print(output_file)

Day 7 workbook saved successfully:
patient_disease_medicine_data.xlsx

In [38]:
if output_file.exists():

    print("Output file exists:", True)
    print("Output file:", output_file)

    saved_excel = pd.ExcelFile(output_file)

    print("\nSaved sheets:")
    print(saved_excel.sheet_names)

else:
    raise FileNotFoundError(
        "Day 7 output workbook was not created."
    )

Output file exists: True
Output file: patient_disease_medicine_data.xlsx

Saved sheets:
['Patient_Disease_Medicine', 'Disease_Medicine_Map', 'Patient_Disease', 'Disease_Patient_Summary', 'Disease_Summary', 'Medicine_Summary', 'Medicine_Distribution', 'Disease_Medicine_Counts', 'Validation_Report']

In [39]:
print("=" * 70)
print("DAY 7 — PATIENT–DISEASE–MEDICINE DATA PREPARATION")
print("=" * 70)

print(f"Total records: {len(patient_disease_medicine_unique)}")
print(
    f"Unique patients: "
    f"{patient_disease_medicine_unique['patient_id'].nunique()}"
)
print(
    f"Unique diseases/conditions: "
    f"{patient_disease_medicine_unique['disease'].nunique()}"
)
print(
    f"Unique medication classes: "
    f"{patient_disease_medicine_unique['medicine_class'].nunique()}"
)

print("\nOutput file:")
print(output_file)

print("\nDay 7 completed successfully.")

======================================================================
DAY 7 — PATIENT–DISEASE–MEDICINE DATA PREPARATION
======================================================================
Total records: 500
Unique patients: 500
Unique diseases/conditions: 6
Unique medication classes: 12

Output file:
patient_disease_medicine_data.xlsx

Day 7 completed successfully.